### ISSUE TITLE
Masternode cannot be started remotely, because hot wallet is locking coins

### ISSUE THREAD

**Issue by M1chlCZ** [SaltineChips/CampusCash#18]
There is an issue with locking coins in wallet, so VPS does not see the MN Tx. Basic manual unlock of the coins and then starting of the MN works, however it should not be that way.

There procedure which allows MN to be started remotely with this bug:

In QT wallet: Send tab > Inputs > click on the plus of MN address which cannot be started > right click on the grey number of locked coins > unlock unspent > Tab Masternodes > Click on Start on specificic MN (or just click start all)
 
On VPS: `mnstart` or ./CampusCashd masternode start

**Comment by SaltineChips** [comment]
You're supposed to control the masternode cold wallet via the hot wallet. Locked inputs are effectively treated as non-existent, this is the purpose of locking an input; otherwise, your wallet can use the inputs.
